### ISSUE TITLE
Does this feed shows to Sonarr?

### ISSUE THREAD

**Issue by jkproperties** [preram48/sonarr-trakt-tv#5]
Hi Guys,
Does this feed new series to download in Sonarr?

**Comment by jkproperties** [comment]
I have managed to install, but cannot run the commands under docker or the tests.

**Comment by jkproperties** [comment]
It is working, doesn't add to Sonarr, but downloads in my client.
This is great,
Thank you,

**Comment by metaMMA** [comment]
I think you might want to check again. This application does not send anything to your download client. Sonarr is the one that does the searching and then sending.
